# Site settings
title: tanveerk.dev
email: your-email@example.com
description: >-
  Welcome to Tanveer's Tech Hub â€” Exploring Embedded Systems, IoT, Smart Grid 
  Innovations, and Arduino tutorials. Join the journey of an EEE student 
  passionate about technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tanveerk.dev" # the base hostname & protocol for your site
twitter_username: itzzveer
github_username: KMTanVeer
instagram_username: itzzveer

# Author info
author:
  name: Kawsar Mahmud Tanveer Khan
  email: your-email@example.com
  bio: "in IoT | Embedded Systems | PLC | Electronics | Electrical Engineering"
  avatar: "/assets/img/about.jpg"
  social:
    linkedin: "https://www.linkedin.com/in/kawsartanveer/"
    github: "https://github.com/KMTanVeer"
    instagram: "https://www.instagram.com/itzzveer/"
    facebook: "https://www.facebook.com/itzzVeer/"
    twitter: "https://x.com/itzzveer"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Pagination
paginate: 6
paginate_path: "/blog/page:num/"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Default layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Kawsar Mahmud Tanveer Khan"
  - scope:
      path: ""
    values:
      layout: "default"

# Site navigation
navigation:
  - title: Home
    url: /
  - title: About
    url: /about.html
  - title: Blog
    url: /blog/
  - title: Projects
    url: /projects.html
  - title: Resources
    url: /resources.html
  - title: Contact
    url: /contact.html
